#!/usr/bin/env python
# coding: utf-8

# In[1]:


from tkinter import Tk
from tkinter import filedialog


# In[2]:


def get_lines():
    lines = []
    root = Tk()
    root.attributes("-topmost", True)
    root.withdraw()
    for file in filedialog.askopenfilenames():
        for line in open(file, encoding="utf-8"):
            yield line
                
def convert(text,to_type):
    try:
        if to_type == "Date":
            return text[-2:]+"/"+text[4:6]+"/"+text[:4]
        elif to_type == "Int":
            return str(int(text))
        elif to_type == "Str":
            return text
        elif to_type == "Float":
            return str(float(text.replace(",","."))).replace(".",",")
    except:
        return text


# In[3]:


headers = {}
headers[376] = ["ESRSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "TPMOID",
                "CMPID",
                "RAMCODIGO",
                "ESRDATAINICIO",
                "ESRDATAFIM",
                "ESRDATAOCORR",
                "ESRDATAREG",
                "ESRVALORMOV",
                "ESRDATACOMUNICA",
                "ESRCODCESS",
                "ESRNUMSIN",
                "ESRVALORMON",
                ]
headers[377] = ["ESLSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "CMPID",
                "RAMCODIGO",
                "ESLDATAINICIO",
                "ESLDATAFIM",
                "ESLDATAOCORR",
                "ESLDATAREG",
                "ESLVALORMOV",
                "ESLCODCESS",
                "ESLNUMSIN",
                ]
headers[378] = ["ESPSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "TPMOID",
                "CMPID",
                "RAMCODIGO",
                "ESPDATAINICIORO",
                "ESPDATAFIMRO",
                "ESPDATAEMISSRO",
                "ESPVALORMOVRO",
                "ESPDATAINICIORD",
                "ESPDATAFIMRD",
                "ESPDATAEMISSRD",
                "ESPVALORMOVRD",
                "ESPCODCESS",
                "ESPFREQ",
                "ESPVALORCARO",
                "ESPVALORCARD",
                "ESPVALORCIRO",
                "ESPVALORCIRD",
                "ESPMOEDA",
                ]
headers[379] = ["EBISEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "TPMOID",
                "TPMOPREV",
                "CMPID",
                "PLNCODIGO",
                "EBINUMPROP",
                "EBICPFPART",
                "EBICPFBENF",
                "EBIDATAINICIO",
                "EBIDATAFIM",
                "EBIDATAOCORR",
                "EBIDATAREG",
                "EBIDATACOMUNICA",
                "EBIBENVEN",
                "EBIVALORPBAC",
                "EBIVALORPBC",
                "EBIVALORMOV",
                "EBIVALORMON",
                "EBICODCESS",
                "EBINUMSIN",
                ]
headers[380] = ["EBRSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "CMPID",
                "PLNCODIGO",
                "EBRNUMPROP",
                "EBRCPFPART",
                "EBRCPFBENF",
                "EBRDATAINICIO",
                "EBRDATAFIM",
                "EBRDATAOCORR",
                "EBRDATAREG",
                "EBRVALORMOV",
                "EBRCODCESS",
                "EBRNUMSIN",
                ]
headers[381] = ["PBCSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "PBCCPFPARTIC",
                "PBCIDADE",
                "PBCVALORBENEF",
                "PBCVALORRESER",
                "PLNCODIGO",
                "TPEVID",
                "TPRENID",
                "TBOID",
                "PBCTAXAJUROS",
                "TFCID",
                "PBCNUMRECEBAN",
                "PBCMESRENDA13",
                "TFPID",
                "PBCTEMPORECEB",
                "PBCTEMPORARIE",
                "PBCIDADBENREV",
                "TBOIDBENREV",
                "PBCPERCREV",
                "PBCDATULTATU",
                "PRAID",
                "INDID",
                "DFAID",
                "PRDREVEXCED",
                "PERCREVEXCED",
                "FORMAREV",

                ]
headers[382] = ["ESCSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "TPMOID",
                "CMPID",
                "PLNCODIGO",
                "ESCDATAINICIORO",
                "ESCDATAFIMRO",
                "ESCDATAEMISSRO",
                "ESCVALORMOVRO",
                "ESCDATAINICIORD",
                "ESCDATAFIMRD",
                "ESCDATAEMISSRD",
                "ESCVALORMOVRD",
                "ESCIMPSEG",
                "ESCCODCESS",
                "ESCFREQ",
                "ESCVALORCARO",
                "ESCVALORCARD",
                "ESCVALORCIRO",
                "ESCVALORCIRD",
                ]
headers[404] = ["MSASEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "TPMORESSID",
                "GRACODIGO",
                "MSATIPOPERA",
                "MSANUMSIN",
                "MSANUMCONT",
                "MSATIPOCONT",
                "MSACODCESS",
                "MSADATACOMUNICA",
                "MSADATAREG",
                "MSADATAOCORR",
                "MSAVALORMOV",
                "MSATIPOSIN",
                "MSAMODCONT",
                "MSAMOEDA",
                "MSABASEIND",
                "MSAVALORMON",
                ]
headers[405] = ["MSRSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "TPMORESSID",
                "GRACODIGO",
                "MSRNUMSIN",
                "MSRNUMCONT",
                "MSRTIPOCONT",
                "MSRCODCESS",
                "MSRDATACOMUNICA",
                "MSRDATAREG",
                "MSRDATAOCORR",
                "MSRVALORMOV",
                "MSRTIPOSIN",
                "MSRMODCONT",
                "MSRMOEDA",
                "MSRBASEIND",
                "MSRVALORMON",
                ]
headers[406] = ["SLASEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "GRACODIGO",
                "SLATIPOPERA",
                "SLANUMSIN",
                "SLANUMCONT",
                "SLATIPOCONT",
                "SLACODCESS",
                "SLADATACOMUNICA",
                "SLADATAREG",
                "SLADATAOCORR",
                "SLAVALORMOVPEN",
                "SLAVALORMOVTOT",
                "SLATIPOSIN",
                "SLAMODCONT",
                "SLAMOEDA",
                "SLABASEIND",
                ]
headers[407] = ["SLRSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "GRACODIGO",
                "SLRNUMSIN",
                "SLRNUMCONT",
                "SLRTIPOCONT",
                "SLRCODCESS",
                "SLRDATACOMUNICA",
                "SLRDATAREG",
                "SLRDATAOCORR",
                "SLRVALORMOVPEN",
                "SLRVALORMOVTOT",
                "SLRTIPOSIN",
                "SLRMODCONT",
                "SLRMOEDA",
                "SLRBASEIND",
                ]
headers[408] = ["MPASEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "TPMORESSID",
                "GRACODIGO",
                "MPATIPOPERA",
                "MPANUMCONT",
                "MPANUMENDOSSO",
                "MPACODCESS",
                "MPATIPOCONT",
                "MPAMODCONT",
                "MPADATAORDEMFIRME",
                "MPADATACONTR",
                "MPADATAINICIO",
                "MPADATAFIM",
                "MPAVALORMOV",
                "MPAPERCENTRISCO",
                "MPAVALORMOVCOMIS",
                "MPAVALORMOVCORRET",
                "MPACODCORRET",
                "MPAVIGMED",
                "MPABASEIND",
                "MPAMOEDA",
                "MPATAXACONV",
                "MPADATAEMISS",
                ]
headers[409] = ["MPRSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "TPMORESSID",
                "GRACODIGO",
                "MPRNUMCONT",
                "MPRNUMENDOSSO",
                "MPRCODESS",
                "MPRTIPOCONT",
                "MPRMODCONT",
                "MPRDATACEITE",
                "MPRDATACONTR",
                "MPRDATAINICIO",
                "MPRDATAFIM",
                "MPRPERCRISCO",
                "MPRVALORMOV",
                "MPRVALORMOVCOMIS",
                "MPRCODCORRET",
                "MPRVALORMOVCORRET",
                "MPRVIGMED",
                "MPRBASEIND",
                "MPRMOEDA",
                "MPRTAXACONV",
                "MPRDATAEMISS",
                ]
headers[419] = ["EMFSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "ATVCODIGO",
                "TPFOPERADOR",
                "FTRCODIGO",
                "LCRCODIGO",
                "TCTCODIGO",
                "TPECODIGO",
                "EMFPRAZOFLUXO",
                "EMFVLREXPRISCO",
                "EMFCNPJFUNDO",
                "EMFCODISIN",
                "EMFCODCUSTODIA",
                "EMFMULTIPLOFATOR",
                "EMFTXCONTRATADO",
                "EMFTXMERCADO",
                "TPFOPERADORDERIVATIVO",
                "EMFVLRDERIVATIVO",
                "EMFCODGRUPO",
                ]
headers[420] = ["EMCSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "DOCCODIGO",
                "TPFOPERADOR",
                "FTRCODIGO",
                "EMCPRAZOFLUXO",
                "EMCVLREXPRISCO",
                "EMCMULTIPLOFATOR",
                "EMCCODGRUPO",
                "EMCSEMREGISTRO",
                ]
headers[421] = ["EMDSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "DODCODIGO",
                "TPFOPERADOR",
                "FTRCODIGO",
                "EMDPRAZOFLUXO",
                "EMDVLREXPRISCO",
                "EMDMULTIPLOFATOR",
                ]
headers[422] = ["EMESEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "EMECODGRUPO",
                "EMEPEF",
                "EMEVLRCONTATIVOS",
                "EMEPERCREVERSAO",
                "EMEPERCDEDUCAO",
                ]
headers[423] = ["EMGSEQ",
                "ENTCODIGO",
                "MRFMESANO",
                "QUAID",
                "EMGCODGRUPO",
                "RAMCODIGO",
                "PLNCODIGO",
                ]


# In[4]:


references = {}
references[376] = [(0, 7, "Int"),
                   (7, 12, "Int"),
                   (12, 20, "Date"),
                   (20, 23, "Int"),
                   (23, 27, "Int"),
                   (27, 31, "Int"),
                   (31, 35, "Int"),
                   (35, 43, "Date"),
                   (43, 51, "Date"),
                   (51, 59, "Date"),
                   (59, 67, "Date"),
                   (67, 80, "Float"),
                   (80, 88, "Date"),
                   (88, 93, "Int"),
                   (93, 113, "Int"),
                   (113, 126, "Float"),
                   ]
references[377] = [(0, 7, "Int"),
                   (7, 12, "Int"),
                   (12, 20, "Date"),
                   (20, 23, "Int"),
                   (23, 27, "Int"),
                   (27, 31, "Int"),
                   (31, 39, "Date"),
                   (39, 47, "Date"),
                   (47, 55, "Date"),
                   (55, 63, "Date"),
                   (63, 76, "Float"),
                   (76, 81, "Int"),
                   (81, 101, "Int"),
                   ]
references[378] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 20, "Str"),
                   (20, 23, "Str"),
                   (23, 27, "Str"),
                   (27, 31, "Str"),
                   (31, 35, "Str"),
                   (35, 43, "Str"),
                   (43, 51, "Str"),
                   (51, 59, "Str"),
                   (59, 72, "Str"),
                   (72, 80, "Str"),
                   (80, 88, "Str"),
                   (88, 96, "Str"),
                   (96, 109, "Str"),
                   (109, 114, "Str"),
                   (114, 118, "Str"),
                   (118, 131, "Str"),
                   (131, 144, "Str"),
                   (144, 157, "Str"),
                   (157, 170, "Str"),
                   (170, 173, "Str"),
                   ]
references[379] = [(0, 7, "Int"),
                   (7, 12, "Int"),
                   (12, 20, "Date"),
                   (20, 23, "Int"),
                   (23, 27, "Int"),
                   (27, 31, "Int"),
                   (31, 35, "Int"),
                   (35, 41, "Int"),
                   (41, 62, "Int"),
                   (62, 73, "Int"),
                   (73, 84, "Int"),
                   (84, 92, "Date"),
                   (92, 100, "Date"),
                   (100, 108, "Date"),
                   (108, 116, "Date"),
                   (116, 124, "Date"),
                   (124, 128, "Int"),
                   (128, 141, "Float"),
                   (141, 154, "Float"),
                   (154, 167, "Float"),
                   (167, 180, "Float"),
                   (180, 185, "Int"),
                   (185, 205, "Int"),


                   ]
references[380] = [(0, 7, "Int"),
                   (7, 12, "Int"),
                   (12, 20, "Date"),
                   (20, 23, "Int"),
                   (23, 27, "Int"),
                   (27, 33, "Int"),
                   (33, 54, "Int"),
                   (54, 65, "Int"),
                   (65, 76, "Int"),
                   (76, 84, "Date"),
                   (84, 92, "Date"),
                   (92, 100, "Date"),
                   (100, 108, "Date"),
                   (108, 121, "Float"),
                   (121, 126, "Int"),
                   (126, 146, "Int")
                   ]
references[381] = [(0, 6, "Int"),
                   (6, 11, "Int"),
                   (11, 19, "Date"),
                   (19, 22, "Int"),
                   (22, 33, "Str"),
                   (33, 37, "Int"),
                   (37, 53, "Float"),
                   (53, 69, "Float"),
                   (69, 75, "Int"),
                   (75, 76, "Int"),
                   (76, 78, "Int"),
                   (78, 80, "Str"),
                   (80, 85, "Float"),
                   (85, 86, "Str"),
                   (86, 88, "Str"),
                   (88, 90, "Str"),
                   (90, 91, "Str"),
                   (91, 95, "Str"),
                   (95, 99, "Str"),
                   (99, 103, "Str"),
                   (103, 105, "Str"),
                   (105, 111, "Str"),
                   (111, 119, "Date"),
                   (119, 121, "Str"),
                   (121, 122, "Str"),
                   (122, 123, "Str"),
                   (123, 126, "Str"),
                   (126, 132, "Str"),
                   (132, 133, "Str")
                   ]
references[382] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 20, "Str"),
                   (20, 23, "Str"),
                   (23, 27, "Str"),
                   (27, 31, "Str"),
                   (31, 37, "Str"),
                   (37, 45, "Str"),
                   (45, 53, "Str"),
                   (53, 61, "Str"),
                   (61, 74, "Str"),
                   (74, 82, "Str"),
                   (82, 90, "Str"),
                   (90, 98, "Str"),
                   (98, 111, "Str"),
                   (111, 127, "Str"),
                   (127, 132, "Str"),
                   (132, 136, "Str"),
                   (136, 149, "Str"),
                   (149, 162, "Str"),
                   (162, 175, "Str"),
                   (175, 188, "Str"),
                   ]
references[404] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 18, "Str"),
                   (18, 21, "Str"),
                   (21, 23, "Str"),
                   (23, 24, "Str"),
                   (24, 44, "Str"),
                   (44, 70, "Str"),
                   (70, 71, "Str"),
                   (71, 76, "Str"),
                   (76, 84, "Str"),
                   (84, 92, "Str"),
                   (92, 100, "Str"),
                   (100, 113, "Str"),
                   (113, 114, "Str"),
                   (114, 116, "Str"),
                   (116, 119, "Str"),
                   (119, 120, "Str"),
                   (120, 133, "Str"),
                   ]
references[405] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 18, "Str"),
                   (18, 21, "Str"),
                   (21, 23, "Str"),
                   (23, 43, "Str"),
                   (43, 69, "Str"),
                   (69, 70, "Str"),
                   (70, 75, "Str"),
                   (75, 83, "Str"),
                   (83, 91, "Str"),
                   (91, 99, "Str"),
                   (99, 112, "Str"),
                   (112, 113, "Str"),
                   (113, 115, "Str"),
                   (115, 118, "Str"),
                   (118, 119, "Str"),
                   (119, 132, "Str"),

                   ]
references[406] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 18, "Str"),
                   (18, 20, "Str"),
                   (20, 21, "Str"),
                   (21, 41, "Str"),
                   (41, 67, "Str"),
                   (67, 68, "Str"),
                   (68, 73, "Str"),
                   (73, 81, "Str"),
                   (81, 89, "Str"),
                   (89, 97, "Str"),
                   (97, 110, "Str"),
                   (110, 123, "Str"),
                   (123, 124, "Str"),
                   (124, 126, "Str"),
                   (126, 129, "Str"),
                   (129, 130, "Str"),
                   ]
references[407] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 18, "Str"),
                   (18, 20, "Str"),
                   (20, 40, "Str"),
                   (40, 66, "Str"),
                   (66, 67, "Str"),
                   (67, 72, "Str"),
                   (72, 80, "Str"),
                   (80, 88, "Str"),
                   (88, 96, "Str"),
                   (96, 109, "Str"),
                   (109, 122, "Str"),
                   (122, 123, "Str"),
                   (123, 125, "Str"),
                   (125, 128, "Str"),
                   (128, 129, "Str"),
                   ]
references[408] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 18, "Str"),
                   (18, 21, "Str"),
                   (21, 23, "Str"),
                   (23, 24, "Str"),
                   (24, 50, "Str"),
                   (50, 56, "Str"),
                   (56, 61, "Str"),
                   (61, 62, "Str"),
                   (62, 64, "Str"),
                   (64, 72, "Str"),
                   (72, 80, "Str"),
                   (80, 88, "Str"),
                   (88, 96, "Str"),
                   (96, 109, "Str"),
                   (109, 115, "Str"),
                   (115, 128, "Str"),
                   (128, 141, "Str"),
                   (141, 146, "Str"),
                   (146, 148, "Str"),
                   (148, 149, "Str"),
                   (149, 152, "Str"),
                   (152, 165, "Str"),
                   (165, 173, "Str"),
                   ]
references[409] = [(0, 7, "Str"),
                   (7, 12, "Str"),
                   (12, 18, "Str"),
                   (18, 21, "Str"),
                   (21, 23, "Str"),
                   (23, 49, "Str"),
                   (49, 55, "Str"),
                   (55, 60, "Str"),
                   (60, 61, "Str"),
                   (61, 63, "Str"),
                   (63, 71, "Str"),
                   (71, 79, "Str"),
                   (79, 87, "Str"),
                   (87, 95, "Str"),
                   (95, 101, "Str"),
                   (101, 114, "Str"),
                   (114, 127, "Str"),
                   (127, 132, "Str"),
                   (132, 145, "Str"),
                   (145, 147, "Str"),
                   (147, 148, "Str"),
                   (148, 151, "Str"),
                   (151, 164, "Str"),
                   (164, 172, "Str"),
                   ]
references[419] = [(0, 6, "Str"),
                   (6, 11, "Str"),
                   (11, 19, "Str"),
                   (19, 22, "Str"),
                   (22, 27, "Str"),
                   (27, 28, "Str"),
                   (28, 31, "Str"),
                   (31, 34, "Str"),
                   (34, 36, "Str"),
                   (36, 40, "Str"),
                   (40, 45, "Str"),
                   (45, 60, "Str"),
                   (60, 74, "Str"),
                   (74, 86, "Str"),
                   (86, 98, "Str"),
                   (98, 99, "Str"),
                   (99, 105, "Str"),
                   (105, 111, "Str"),
                   (111, 112, "Str"),
                   (112, 127, "Str"),
                   (127, 133, "Str"),
                   ]
references[420] = [(0, 6, "Str"),
                   (6, 11, "Str"),
                   (11, 19, "Str"),
                   (19, 22, "Str"),
                   (22, 27, "Str"),
                   (27, 28, "Str"),
                   (28, 31, "Str"),
                   (31, 36, "Str"),
                   (36, 51, "Str"),
                   (51, 52, "Str"),
                   (52, 58, "Str"),
                   (58, 59, "Str"),

                   ]
references[421] = [(0, 6, "Str"),
                   (6, 11, "Str"),
                   (11, 19, "Str"),
                   (19, 22, "Str"),
                   (22, 27, "Str"),
                   (27, 28, "Str"),
                   (28, 31, "Str"),
                   (31, 36, "Str"),
                   (36, 51, "Str"),
                   (51, 52, "Str"),
                   ]
references[422] = [(0, 6, "Str"),
                   (6, 11, "Str"),
                   (11, 19, "Str"),
                   (19, 22, "Str"),
                   (22, 28, "Str"),
                   (28, 43, "Str"),
                   (43, 58, "Str"),
                   (58, 64, "Str"),
                   (64, 70, "Str"),
                   ]
references[423] = [(0, 6, "Str"),
                   (6, 11, "Str"),
                   (11, 19, "Str"),
                   (19, 22, "Str"),
                   (22, 28, "Str"),
                   (28, 32, "Str"),
                   (32, 38, "Str"),
                   ]


# In[5]:


def export_to_csv(qe):
    with open(f"{qe}_formatted.csv", "a+", encoding="utf-8") as csv:
        csv.write(";".join(headers[qe])+"\n")
        for line in get_lines():
            if line not in ["\n", None]:
                line = line.strip()
                data = [convert(line[i:x],z) for i, x, z in references[qe]]
                csv.write(";".join(data)+"\n")

for i in [376, 377]:
    export_to_csv(i)


# In[ ]:





# In[ ]:




